# Packages

In [1]:
import statistics
import numpy as np

# Basics

In [5]:
def contract(shares, price, win):
    amt = 0
    profit_fee = .9
    if win:
        amt = profit_fee*(shares - shares*price)+shares*price
    return amt

def withdraw(x):
    withdrawal_fee = .05
    return (1-withdrawal_fee)*x

def tax(winnings):
    federal_gambling_tax = .24
    state_income_tax = .04
    winnings = winnings*(1-state_income_tax)*(1-federal_gambling_tax)
    return winnings
    
def predictit(contracts):
    initial_investment = 0
    total = 0
    for x in contracts:
        initial_investment = initial_investment + x[0]*x[1]
        total = total + contract(x[0], x[1], x[2])
    total = withdraw(total)
    if total > initial_investment:
        total = tax(total-initial_investment) + initial_investment
    return total

In [7]:
predictit([[403,.94,True]])

380.08432383999997

# Hedge

In [14]:
def hedge(priceHedge, priceOrigin, hedgePercent, investmentTotal):
    xMargin = .9*(1/priceHedge-1)
    yMargin = .9*(1/priceOrigin-1)
    x = hedgePercent*investmentTotal
    y = investmentTotal - x
    cost = [x*xMargin - y, y*yMargin - x]
    return cost
def hedgeOpp(priceHedge, priceOrigin, hedgePercent, investmentTotal):
    xMargin = .9*(1/priceHedge-1)
    yMargin = .9*(1/priceOrigin-1)
    x = hedgePercent*investmentTotal
    y = investmentTotal - x
    cost = [x*xMargin - y >= 0, y*yMargin - x >= 0]
    return sum(cost)==2

In [41]:
tries = np.linspace(0,100)*.01
results = np.array([[np.round(hedge(.17, .75, perc, 1000),2)] + [np.round(perc,2)] for perc in tries])
results

array([[array([-1000.,   300.]), 0.0],
       [array([-889.92,  273.47]), 0.02],
       [array([-779.83,  246.94]), 0.04],
       [array([-669.75,  220.41]), 0.06],
       [array([-559.66,  193.88]), 0.08],
       [array([-449.58,  167.35]), 0.1],
       [array([-339.5 ,  140.82]), 0.12],
       [array([-229.41,  114.29]), 0.14],
       [array([-119.33,   87.76]), 0.16],
       [array([-9.24, 61.22]), 0.18],
       [array([100.84,  34.69]), 0.2],
       [array([210.92,   8.16]), 0.22],
       [array([321.01, -18.37]), 0.24],
       [array([431.09, -44.9 ]), 0.27],
       [array([541.18, -71.43]), 0.29],
       [array([651.26, -97.96]), 0.31],
       [array([ 761.34, -124.49]), 0.33],
       [array([ 871.43, -151.02]), 0.35],
       [array([ 981.51, -177.55]), 0.37],
       [array([1091.6 , -204.08]), 0.39],
       [array([1201.68, -230.61]), 0.41],
       [array([1311.76, -257.14]), 0.43],
       [array([1421.85, -283.67]), 0.45],
       [array([1531.93, -310.2 ]), 0.47],
       [array

In [39]:
tries = np.linspace(0,100)*.01
results = np.array([[hedgeOpp(.45, .75, perc, 1000)] + [np.round(perc,2)] for perc in tries])
[x for x in results]


[array([0., 0.]),
 array([0.  , 0.02]),
 array([0.  , 0.04]),
 array([0.  , 0.06]),
 array([0.  , 0.08]),
 array([0. , 0.1]),
 array([0.  , 0.12]),
 array([0.  , 0.14]),
 array([0.  , 0.16]),
 array([0.  , 0.18]),
 array([0. , 0.2]),
 array([0.  , 0.22]),
 array([0.  , 0.24]),
 array([0.  , 0.27]),
 array([0.  , 0.29]),
 array([0.  , 0.31]),
 array([0.  , 0.33]),
 array([0.  , 0.35]),
 array([0.  , 0.37]),
 array([0.  , 0.39]),
 array([0.  , 0.41]),
 array([0.  , 0.43]),
 array([0.  , 0.45]),
 array([0.  , 0.47]),
 array([0.  , 0.49]),
 array([0.  , 0.51]),
 array([0.  , 0.53]),
 array([0.  , 0.55]),
 array([0.  , 0.57]),
 array([0.  , 0.59]),
 array([0.  , 0.61]),
 array([0.  , 0.63]),
 array([0.  , 0.65]),
 array([0.  , 0.67]),
 array([0.  , 0.69]),
 array([0.  , 0.71]),
 array([0.  , 0.73]),
 array([0.  , 0.76]),
 array([0.  , 0.78]),
 array([0. , 0.8]),
 array([0.  , 0.82]),
 array([0.  , 0.84]),
 array([0.  , 0.86]),
 array([0.  , 0.88]),
 array([0. , 0.9]),
 array([0.  , 0.92]),


In [20]:
hedgeOpp(.1, .75, .05, 1000)

False

In [137]:
tries[indices]

array([0.75510204, 0.7755102 , 0.79591837, 0.81632653, 0.83673469,
       0.85714286, 0.87755102, 0.89795918, 0.91836735, 0.93877551,
       0.95918367, 0.97959184, 1.        ])

In [164]:
np.round(hedge(.42, .75, .75, 846.71), 2)

array([ 577.58, -571.53])

In [162]:
"wow"[0:2]

'wo'